version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "provider/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "gomod"
    directory: "sdk/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
ignore:
  - dependency-name: "@angular*"
    update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"