version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "provider/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "gomod"
    directory: "sdk/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all"
