version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "provider/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "direct"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
        - "*"
        exclude-patterns:
        - "github.com/pulumi/pulumi*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "gomod"
    directory: "sdk/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "direct"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
        - "*"
        exclude-patterns:
        - "github.com/pulumi/pulumi*"
        update-types:
        - "minor"
        - "patch"
